### ISSUE TITLE
Support for analog pins for multiple buttons

### ISSUE THREAD

**Issue by cazzoo** [JSC-electronics/ObjectButton#5]
**Is your feature request related to a problem? Please describe.**
I wonder if this is possible to adapt your library to support multiple buttons in the same analog Pin.
Some other library implemented such design (https://github.com/rlogiacco/AnalogButtons), but doesn't handle the evens the way you do it and I wonder if there might be a way to do it using your library.

**Describe the solution you'd like**
Provide the ability to use an analog PIN, then allow a button to be configured with an activation value that triggers it (between 0 and 1024, based on the resistor associated with the button with a margin for resistor variance). 

**Additional context**
I tried to do it myself but I'm clearly lacking knowledge... Do you think this can be done ?

**Comment by vzahradnik** [comment]
Hi @cazzoo, I think it's doable and I will look into it probably during some weekend. Make sure you stay subscribed to this issue and when I'll have something to test, I will post an update here.

**Comment by cazzoo** [comment]
That's awesome, I'll look forward very closely to this. Do not hesitate to use branches, i'm pretty much used to git tool :)
See you

**Comment by vzahradnik** [comment]
@cazzoo that's great! I will provide my changes in a separate branch and maybe you could help with testing. At the moment I code more in Python and other languages but it will be fun to do C++ again.

**Comment by cazzoo** [comment]
Hey! Did you had chance to get a look on it ?

**Comment by vzahradnik** [comment]
@cazzoo Hi, I was just thinking on it yesterday. Sadly, no. I work on other projects now, but it is on my TODO list. I'll definitely let you know if there's some progress.

**Comment by cazzoo** [comment]
Good to hear! 
Just let me know, I'd be glad to help if possible.
Cheers

**Comment by vzahradnik** [comment]
@cazzoo I just started working on this feature, finally! A couple of notes:
- New version will break compatibility; I will bump version code to 2.0.0. In case you use PlatformIO, you can specify exact library version to download; hence, your code will still work
- I introduced components AnalogButton, AnalogSensor, DigitalButton, and DigitalSensor
- Sensors are just rebranded buttons. We use ObjectButton for detecting sensor changes as well, this should better clarify such a usecase
- AnalogButtons/Sensors will have a couple of limitations. For example, you won't be able to press multiple buttons at the same time (the library you referenced works the same)

Anyway, in a few days I should have something to test. If you want, you can track the progress [here](/JSC-electronics/ObjectButton/tree/feature/analog-button).

I will update this issue as well.

Cheers

**Comment by cazzoo** [comment]
🤩 Wonderful news! I just finished to test my wiring for gauges and 7-segment LCDs, now will have to hook up on the button box.
Using platformIO too so will probably in position to get everything from here.
In the end, I'll probably propose a plug-in/extension for simhub to embed your library if you grant me the ability to do so. All credits goes to you anyway. If you're against, I can keep all my implementation for myself without any problem

**Comment by vzahradnik** [comment]
@cazzoo SimHub looks cool! Thanks for pointing it out. Of course you can use our library, it's open-source after-all.

**Comment by vzahradnik** [comment]
@cazzoo this feature is implemented. Feel free to [test](https://github.com/JSC-electronics/ObjectButton/tree/feature/analog-button).

I added new examples showing how to configure analog buttons/sensors. It should be pretty clear. If you find something to improve, please let me know.

**Comment by vzahradnik** [comment]
Merged into master.

**Comment by cazzoo** [comment]
Wow! That was a quick implementation!
I'll try to test is soon and will give you feedback as soon as I can.
Kindly regards and good job!

**Comment by vzahradnik** [comment]
You're welcome. I agreed with my colleague that support for analog buttons could be useful even for us, and now I had some time to implement it.

I already use this new version in one project, and it seems digital buttons are still working fine. So today I merged changes into master branch.

Now, we'll test this new version, and maybe in a month we'll create a release. If you find anything to improve, feel free to report.

**Comment by vzahradnik** [comment]
I just published a new release with all the changes. I will close this issue as RESOLVED. If you find any bugs, feel free to comment here, or open a new issue.
